# Generated by Django 3.2.8 on 2021-11-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-sent_date']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='professionalID',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='when',
        ),
        migrations.AddField(
            model_name='appointment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sent_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
