# Generated by Django 3.2.8 on 2021-12-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20211204_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='on_demand',
            field=models.BooleanField(default=True),
        ),
    ]
