# Generated by Django 3.2.8 on 2021-12-05 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='health_professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HealthProfessional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
