# Generated by Django 3.2.8 on 2021-12-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20211205_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='health_professional',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='health_professional_username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
